export const GET_BOARD_SPACE_INFO = "GET_BOARD_SPACE_INFO";
export const CREATE_ENTITY = "CREATE_ENTITY";
export const DESTROY_ENTITY = "DESTROY_ENTITY";
export const PERFORM_ENTITY_SELF_ACTION = "PERFORM_ENTITY_SELF_ACTION";
export const FILL_BOARD_WITH_ENTITY_TYPE = "FILL_BOARD_WITH_ENTITY_TYPE";


export const UPDATE_SELF = "UPDATE_SELF";
// UPDATE_TARGET_ENTITY
// MOVE_SELF_TO_TARGET
// CREATE_ENTITY_AT_TARGET
// SELF_DESTRUCT ?